# Generated by Django 5.1.3 on 2024-11-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tablero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tecnico",
                    models.CharField(max_length=100, verbose_name="Técnico a cargo"),
                ),
                ("numero_ot", models.CharField(max_length=20, verbose_name="N° OT")),
                ("cliente", models.CharField(max_length=100)),
                (
                    "nombre_tablero",
                    models.CharField(max_length=200, verbose_name="Nombre del Tablero"),
                ),
                ("fecha_entrega", models.DateField(verbose_name="Fecha de Entrega")),
                ("dias_restantes", models.IntegerField(verbose_name="Días restantes")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROCESO", "En Proceso"),
                            ("COMPLETADO", "Completado"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tablero",
                "verbose_name_plural": "Tableros",
            },
        ),
    ]
