# Generated by Django 5.1.3 on 2024-11-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mi_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tablero",
            name="estado",
            field=models.CharField(
                choices=[
                    ("EJECUCION", "Ejecución"),
                    ("TERMINADO", "Terminado"),
                    ("DESPACHADO", "Despachado"),
                ],
                default="EJECUCION",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
    ]
