# Generated by Django 5.1.3 on 2024-11-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mi_app", "0002_alter_tablero_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tablero",
            name="dias_restantes",
            field=models.IntegerField(editable=False, verbose_name="Días restantes"),
        ),
    ]
