# Generated by Django 5.1.3 on 2024-11-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mi_app", "0003_alter_tablero_dias_restantes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tablero",
            name="dias_restantes",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Días restantes"
            ),
        ),
        migrations.AlterField(
            model_name="tablero",
            name="estado",
            field=models.CharField(
                choices=[
                    ("EJECUCION", "Ejecución"),
                    ("EN_PRUEBAS", "En Pruebas"),
                    ("TERMINADO", "Terminado"),
                    ("DESPACHADO", "Despachado"),
                ],
                default="EJECUCION",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
    ]
